language: python

python:
  - 3.6
  - 3.7

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pipenv
  - pip install codecov

install:
  # - pip install ".[test]" . # install package + test dependencies
  - pipenv install

script: coverage run test.py # run the tests

after_success:
  - codecov # submit coverage

