language: python
python:
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pipenv
  - pip install codecov
install:
  # - pip install ".[test]" . # install package + test dependencies
  - pipenv shell
  - pipenv install
script: python -m unittest discover -s ./tests/ -t ./tests -p test_* # run the tests
after_success:
  - codecov # submit coverage

